function sout = rtnanalysis(drtns,dDates,varargin)
% 持仓分析
% 
% - by Lary 2017.01.23

% 季节性分布

sout.vol = std(drtns)*15.6;
sout.sharpe = mean(drtns)./std(drtns)*15.6;

if exist('dDates','var')
    sout.seansonr = [mean(drtns(quarter(dDates)==1));...
                    mean(drtns(quarter(dDates)==2));...
                    mean(drtns(quarter(dDates)==3));...
                    mean(drtns(quarter(dDates)==4))];
    sout.monthr = [mean(drtns(month(dDates)==1));...
                    mean(drtns(month(dDates)==2));...
                    mean(drtns(month(dDates)==3));...
                    mean(drtns(month(dDates)==4));...
                    mean(drtns(month(dDates)==5));...
                    mean(drtns(month(dDates)==6));...
                    mean(drtns(month(dDates)==7));...
                    mean(drtns(month(dDates)==8));...
                    mean(drtns(month(dDates)==9));...
                    mean(drtns(month(dDates)==10));...
                    mean(drtns(month(dDates)==11));...
                    mean(drtns(month(dDates)==12))];
    sout.seansonv = [std(drtns(quarter(dDates)==1));...
                    std(drtns(quarter(dDates)==2));...
                    std(drtns(quarter(dDates)==3));...
                    std(drtns(quarter(dDates)==4))];
    sout.monthv = [std(drtns(month(dDates)==1));...
                    std(drtns(month(dDates)==2));...
                    std(drtns(month(dDates)==3));...
                    std(drtns(month(dDates)==4));...
                    std(drtns(month(dDates)==5));...
                    std(drtns(month(dDates)==6));...
                    std(drtns(month(dDates)==7));...
                    std(drtns(month(dDates)==8));...
                    std(drtns(month(dDates)==9));...
                    std(drtns(month(dDates)==10));...
                    std(drtns(month(dDates)==11));...
                    std(drtns(month(dDates)==12))];
    sout.seansons = sout.seansonr./sout.seansonv*15.6;
    sout.months = sout.monthr./sout.monthv*15.6;
end

end